
/**
 * This class is used to model
 * @author Burak
 */
public class ProfileUI extends javax.swing.JFrame {

    private final User user;
    
    /**
     * Creates new form ProfileUI
     * @param user
     */
    public ProfileUI(User user) {
        initComponents();
        this.user = user;
        updateInformation();
        this.setLocationRelativeTo(null);
    }
    
    private void updateInformation(){
        name.setText(user.getName());
        surname.setText(user.getSurname());
        gender.setText(user.getGender());
        region.setText(user.getRegion());
        balance.setText("" +IncomeChart.round(DataReader.getCurrentNetBalance(user) , 2) + " " + user.getCurrency());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        surname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        region = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(350, 350));

        contentPane.setPreferredSize(new java.awt.Dimension(350, 350));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        contentPane.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 20));

        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("jLabel1");
        contentPane.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 73, 130, 20));

        surname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        surname.setText("jLabel2");
        contentPane.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 116, 130, 20));

        gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gender.setText("jLabel3");
        contentPane.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 20));

        region.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        region.setText("jLabel4");
        contentPane.add(region, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 205, 130, 20));

        balance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balance.setText("jLabel5");
        contentPane.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, 28));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/pics/profileBackground.png"))); // NOI18N
        contentPane.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel close;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel name;
    private javax.swing.JLabel region;
    private javax.swing.JLabel surname;
    // End of variables declaration//GEN-END:variables
}
